### ISSUE TITLE
Graph import GEFX version 1.2 (deprecated) on Gephi 0.9.2

### ISSUE THREAD

**Issue by pcuellar** [OfirKP/Whatsapp-Net#4]
When importing .gexf graph into Gephi 0.9.2, import raises issue 
`GEFX version 1.2 (deprecated)`

Graph seems to be working well but this deprecation will eventually impact the rendering. Only function that is a bit funky is HeatMapping though I can't say for sure it is a result of this deprecation.

**Comment by OfirKP** [comment]
Hey again!
According to the documentation of the latest version of _NetworkX_ (the library I used for graph processing), the latest version currently supported for the output _gexf_ file is `1.2draft`. 

I searched through the open issues in [networkx](https://github.com/networkx/networkx) and found [this](https://github.com/networkx/networkx/pull/3457).  

Could you elaborate more about the heat mapping function that looks funky?

**Comment by pcuellar** [comment]
The heat mapping function on other graphs scales smoothly when zooming within graphs. I replicated this on a different machine and found that the `GEFX version 1.2 (deprecated)` is still being raised, though it doesn't seem to have any impact (at least that I can notice). Heat mapping works well. Closing this issue for now.
